SHELL=/bin/bash

gcd:
	cp ../../comparison_tests/gcd/gcd.hex icache_init.txt

fib:
	cp ../../comparison_tests/fibonacci/fibonacci.hex icache_init.txt
    
matrix:
	cp ../../comparison_tests/matrix/matrix.hex icache_init.txt

all_inst:
	cp ../../comparison_tests/all_inst/all_inst.hex icache_init.txt

